### ISSUE TITLE
Improve color options for tags

### ISSUE THREAD

**Issue by lappalj4** [hackjunction/hackplatform#17]
![image](https://user-images.githubusercontent.com/11797156/71981973-3b1e1b00-322c-11ea-8184-be05cf5aa3ce.png)

This list of possible colors should be updated to include only standard CSS color names (https://www.w3schools.com/colors/colors_names.asp), as the current list is based on the color variants available to Ant Design Tags, which is no longer in use, and some of the color options are non-standard (e.g. "volcano").

Additionally the list item could show a small circle filled with the corresponding color for a quick visual reference.

**Comment by m-murasovs** [comment]
Hi, I'd like to have a go at this.
Would you like the Ant Design Tag colours updated to their CSS equivalents/something similar or just removed?

**Comment by lappalj4** [comment]
Hi! Good to hear, you're most welcome to have a go. I think we'll be fine with around 10-20 basic colors, no need to find equivalents for the Antd ones. Here's the (only) component where these colors are used, so you can check out how that works if you like: https://github.com/hackjunction/hackplatform/blob/master/frontend/src/components/generic/Tag/index.js

I'm currently updating the contribution guide in the README, so make sure to check that out as well.

**Comment by lappalj4** [comment]
Done in #25
