### ISSUE TITLE
Hackerpack description is shown in key: value format

### ISSUE THREAD

**Issue by pholm** [hackjunction/hackplatform#178]
The image is quite self-explanatory

![image](https://user-images.githubusercontent.com/1903693/84031680-cdbf1380-a99e-11ea-9348-5c69f1297beb.png)

**Comment by khenriksson** [comment]
This can be changed from the admin view and is probably just someone copy-pasting wrong, however I did find another bug while trying to save the new description: it's not possible to save.

![image](https://user-images.githubusercontent.com/35761879/84126227-4e851a80-aa46-11ea-8cb0-890d2bbf8021.png)

**Comment by Earlo** [comment]
Ah, yeah, Fixed this. 

It was a copy paste issue, not a bug.
