### ISSUE TITLE
Add a registration form field for Curriculum Vitae

### ISSUE THREAD

**Issue by lappalj4** [hackjunction/hackplatform#23]
We should allow organisers to ask for a Link to CV in their registration form. Essentially this would just require adding a `curriculumVitae` field in [`registration-fields.js`](https://github.com/hackjunction/hackplatform/blob/dev/shared/constants/registration-fields.js), very much similar to the Link to Github/Link to Portfolio/LinkedIn fields under the "Links" category.

**Comment by lappalj4** [comment]
This field could also be copied over to the user profile, and editable under /account/profile. Relevant code here: https://github.com/hackjunction/hackplatform/blob/dev/frontend/src/pages/_account/profile/index.js

**Comment by Earlo** [comment]
Done with #26
