### ISSUE TITLE
Run Prettier on all files in the project

### ISSUE THREAD

**Issue by lappalj4** [hackjunction/hackplatform#46]
Currently diffs are being bloated with commas and other formatting details added/removed by Prettier (if it's a file that hasn't been edited in a while) and it's a bit hard to see what has actually been changed in a file. We should run Prettier with the current config on every file in the project.

**Comment by lappalj4** [comment]
This should probably be done as soon as #45 and #38 have been merged

**Comment by Earlo** [comment]
I was just thinking yesterday that it should had been done before we started any new branches 😅 

If I can speed up the GraphQL branch being merged, let me know.

**Comment by lappalj4** [comment]
So maybe now would be a good time? 😎
