### ISSUE TITLE
Event-specific Open Graph tags

### ISSUE THREAD

**Issue by pholm** [hackjunction/hackplatform#80]
Currently when linked to external sites like Facebook, Telegram etc. the link preview shows very general Junction information and some picture from Dipoli Käpy. 

Would be awesome that this information would be event-specific.

**Comment by pholm** [comment]
https://github.com/nfl/react-helmet this could work

**Comment by lappalj4** [comment]
Only issue here is that unlike Google, Open Graph doesn't really understand React and dynamically generating SEO stuff, so anything dynamically generated won't really work with facebook/twitter shares, unless you feed it through a prerender service first like what's happening on hackjunction.com (prerender.io)
